package com.petcare.petcare.model.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.petcare.petcare.model.entities.CareSchedule;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.PastOrPresent;

import java.time.LocalDate;

public class CareScheduleDTO {

    @Schema(description = "Unique ID of the care schedule generated by the database", example = "2")
    private Long id;

    @PastOrPresent(message = "Last vacination date must be in the past or present.")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
    @Schema(description = "Last vaccine date", example = "10/01/2024")
    private LocalDate lastVacine;

    @FutureOrPresent(message = "Next vacination date must be in the future or present.")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
    private LocalDate nextVacine;

    @Schema(description = "Current medication", example = "Prednisolona 5mg")
    private String currentMedication;

    @Column(columnDefinition = "TEXT")
    @Schema(description = "Additional notes for medication", example = "Administer after meals")
    private String medicationNotes;

    @PastOrPresent(message = "Last appointment date must be in the past or present.")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
    @Schema(description = "Last appointment date", example = "02/08/2024")
    private LocalDate lastAppointment;

    @FutureOrPresent(message = "Next appointment date must be in the future or present.")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
    @Schema(description = "Next appointment date", example = "02/02/2025")
    private LocalDate nextAppointment;

    @Column(columnDefinition = "TEXT")
    @Schema(description = "Appointment notes", example = "Rotina check-up. Tudo ok")
    private String appointmentNotes;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
    @Schema(description = "Last grooming date", example = "11/05/2024")
    private LocalDate lastGrooming;

    @Schema(description = "Grooming type", example = "Banho completo")
    private String grooming;

    @Schema(description = "General notes about pet care", example = "Pet está com boa saúde.")
    private String notes;

    @JsonFormat(shape = JsonFormat.Shape.STRING,
            pattern = "dd/MM/yyyy HH:mm:ss",
            timezone = "America/Sao_Paulo")
    @Schema(description = "Pet information (minimal view)")
    private PetMinDTO petMinDTO;

    public CareScheduleDTO(Long id, LocalDate lastVacine, LocalDate nextVacine, String currentMedication,
                           String medicationNotes, LocalDate lastAppointment, LocalDate nextAppointment,
                           String appointmentNotes, LocalDate lastGrooming, String grooming, String notes) {
        this.id = id;
        this.lastVacine = lastVacine;
        this.nextVacine = nextVacine;
        this.currentMedication = currentMedication;
        this.medicationNotes = medicationNotes;
        this.lastAppointment = lastAppointment;
        this.nextAppointment = nextAppointment;
        this.appointmentNotes = appointmentNotes;
        this.lastGrooming = lastGrooming;
        this.grooming = grooming;
        this.notes = notes;
    }

    public CareScheduleDTO(CareSchedule entity) {
        this.id = entity.getId();
        this.lastVacine = entity.getLastVacine();
        this.nextVacine = entity.getNextVacine();
        this.currentMedication = entity.getCurrentMedication();
        this.medicationNotes = entity.getMedicationNotes();
        this.lastAppointment = entity.getLastAppointment();
        this.nextAppointment = entity.getNextAppointment();
        this.appointmentNotes = entity.getAppointmentNotes();
        this.lastGrooming = entity.getLastGrooming();
        this.grooming = entity.getGrooming();
        this.notes = entity.getNotes();

        if (entity.getPet() != null) {
            this.petMinDTO = new PetMinDTO(entity.getPet());
        }
    }

    public Long getId() {
        return id;
    }

    public LocalDate getLastVacine() {
        return lastVacine;
    }

    public LocalDate getNextVacine() {
        return nextVacine;
    }

    public String getCurrentMedication() {
        return currentMedication;
    }

    public String getMedicationNotes() {
        return medicationNotes;
    }

    public LocalDate getLastAppointment() {
        return lastAppointment;
    }

    public LocalDate getNextAppointment() {
        return nextAppointment;
    }

    public String getAppointmentNotes() {
        return appointmentNotes;
    }

    public LocalDate getLastGrooming() {
        return lastGrooming;
    }

    public String getGrooming() {
        return grooming;
    }

    public String getNotes() {
        return notes;
    }

    public PetMinDTO getPetMinDTO() {
        return petMinDTO;
    }
}
