package com.petcare.petcare.model.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.petcare.petcare.model.entities.Pet;
import com.petcare.petcare.model.enums.Gender;
import com.petcare.petcare.model.enums.Species;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;

import java.time.LocalDate;

public class PetDTO {

    @Schema(description = "Unique ID of the pet generated by the database", example = "1")
    private Long id;

    @Schema(description = "Minimal information about the pet owner")
    private OwnerMinDTO ownerMinDTO;

    @Size(min = 2, max = 30, message = "Name must be between 2 and 30 characters long.")
    @NotBlank(message = "Name cannot be blank.")
    @Schema(description = "Pet name", example = "Bianca")
    private String name;

    @NotNull (message = "Species cannot be blank.")
    @Schema(description = "Pet species (ENUM)", example = "DOG")
    private Species species;

    @Schema(description = "Pet breed", example = "Yorkshire Terrier")
    private String breed;

    @Schema(description = "Pet gender (ENUM)", example = "FEMALE")
    private Gender gender;

    @PastOrPresent(message = "Birth date must be in the past or present.")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
    @Schema(
            description = "Pet birth date in dd/MM/yyyy format",
            example = "26/05/2013"
    )
    private LocalDate birthDate;

    @Positive(message = "Weight must be positive.")
    @Schema(description = "Pet weight in kilograms", example = "3.5")
    private Double weight;

    @Schema(description = "Minimal information about the pet's care schedule")
    private CareScheduleMinDTO careScheduleMinDTO;

    public PetDTO() {
    }

    public PetDTO(Long id, OwnerMinDTO ownerMinDTO, String name, Species species, String breed, Gender gender, LocalDate birthDate, Double weight) {
        this.id = id;
        this.ownerMinDTO = ownerMinDTO;
        this.name = name;
        this.species = species;
        this.breed = breed;
        this.gender = gender;
        this.birthDate = birthDate;
        this.weight = weight;
    }

    public PetDTO(Pet entity) {
        id = entity.getId();
        if (entity.getOwner() != null) {
            this.ownerMinDTO = new OwnerMinDTO(entity.getOwner());
        }
        name = entity.getName();
        species = entity.getSpecies();
        breed = entity.getBreed();
        gender = entity.getGender();
        birthDate = entity.getBirthDate();
        weight = entity.getWeight();

        if (entity.getCareSchedule() != null) {
            this.careScheduleMinDTO = new CareScheduleMinDTO(entity.getCareSchedule());
        }
    }

    public Long getId() {
        return id;
    }

    public OwnerMinDTO getOwnerMinDTO() {
        return ownerMinDTO;
    }

    public String getName() {
        return name;
    }

    public Species getSpecies() {
        return species;
    }

    public String getBreed() {
        return breed;
    }

    public Gender getGender() {
        return gender;
    }

    public LocalDate getBirthDate() {
        return birthDate;
    }

    public Double getWeight() {
        return weight;
    }

    public CareScheduleMinDTO getCareScheduleMinDTO() {
        return careScheduleMinDTO;
    }
}
