package com.petcare.petcare.model.dto;

import com.petcare.petcare.model.entities.Pet;
import io.swagger.v3.oas.annotations.media.Schema;

public class PetMinDTO {

    @Schema(description = "Unique ID of the pet generated by the database")
    private Long id;

    @Schema(description = "Pet name")
    private String name;

    @Schema(description = "Pet breed")
    private String breed;

    @Schema(description = "Pet weight")
    private Double weight;

    public PetMinDTO() {
    }

    public PetMinDTO(Long id, String name, String breed, Double weight) {
        this.id = id;
        this.name = name;
        this.breed = breed;
        this.weight = weight;
    }

    public PetMinDTO(Pet entity) {
        id = entity.getId();
        name = entity.getName();
        breed = entity.getBreed();
        weight = entity.getWeight();
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getBreed() {
        return breed;
    }

    public Double getWeight() {
        return weight;
    }

}
